"""Static topic taxonomy seed data used to populate the topics table."""


def build_seed_topics() -> list[dict]:
    """Build the complete list of seed topics.

    Returns a list of dicts suitable for HorizonDB.seed_topics().
    """
    return [
        # === 公司与模型 ===
        {
            "name": "OpenAI / ChatGPT",
            "slug": "openai-chatgpt",
            "group_name": "公司与模型",
            "description": "OpenAI 旗下产品与模型相关新闻，包括 ChatGPT、GPT 系列、o1/o3、Sora、DALL-E 等",
            "keywords": ["OpenAI", "ChatGPT", "GPT", "GPT-4", "GPT-5", "o1", "o3", "Sora", "DALL-E", "Sam Altman"],
            "aliases": ["openai", "chatgpt", "gpt"],
            "sort_order": 10,
            "is_active": 1,
        },
        {
            "name": "Anthropic / Claude",
            "slug": "anthropic-claude",
            "group_name": "公司与模型",
            "description": "Anthropic 旗下 Claude 系列模型相关新闻",
            "keywords": ["Anthropic", "Claude", "Claude 3", "Claude 4", "Claude 5", "Opus", "Sonnet", "Haiku", "Dario Amodei"],
            "aliases": ["anthropic", "claude"],
            "sort_order": 20,
            "is_active": 1,
        },
        {
            "name": "Google / Gemini",
            "slug": "google-gemini",
            "group_name": "公司与模型",
            "description": "Google DeepMind 旗下 Gemini 系列模型及 AI 产品相关新闻",
            "keywords": ["Google", "Gemini", "DeepMind", "Gemma", "Gemini 2", "Gemini 3", "Veo", "Imagen", "NotebookLM", "Project Mariner"],
            "aliases": ["google", "gemini", "deepmind", "gemma"],
            "sort_order": 30,
            "is_active": 1,
        },
        {
            "name": "DeepSeek",
            "slug": "deepseek",
            "group_name": "公司与模型",
            "description": "深度求索旗下 DeepSeek 系列模型相关新闻",
            "keywords": ["DeepSeek", "DeepSeek-V2", "DeepSeek-V3", "DeepSeek-R1", "DeepSeek-Coder", "幻方量化"],
            "aliases": ["deepseek", "深度求索"],
            "sort_order": 40,
            "is_active": 1,
        },
        {
            "name": "通义千问 Qwen",
            "slug": "qwen",
            "group_name": "公司与模型",
            "description": "阿里云通义千问 Qwen 系列模型相关新闻",
            "keywords": ["Qwen", "通义千问", "Qwen2", "Qwen3", "Qwen-VL", "Qwen-Audio", "阿里云", "阿里巴巴"],
            "aliases": ["qwen", "通义千问", "tongyi", "阿里"],
            "sort_order": 50,
            "is_active": 1,
        },
        {
            "name": "Kimi / 月之暗面",
            "slug": "kimi-moonshot",
            "group_name": "公司与模型",
            "description": "月之暗面 Kimi 系列模型与产品相关新闻",
            "keywords": ["Kimi", "月之暗面", "Moonshot AI", "杨植麟"],
            "aliases": ["kimi", "moonshot", "月之暗面"],
            "sort_order": 60,
            "is_active": 1,
        },
        {
            "name": "MiniMax",
            "slug": "minimax",
            "group_name": "公司与模型",
            "description": "MiniMax（稀宇科技）旗下模型与产品相关新闻",
            "keywords": ["MiniMax", "稀宇科技", "MiniMax-Text", "MiniMax-VL", "海螺AI", "Hailuo AI"],
            "aliases": ["minimax", "稀宇科技", "hailuo"],
            "sort_order": 70,
            "is_active": 1,
        },
        {
            "name": "智谱 GLM",
            "slug": "zhipu-glm",
            "group_name": "公司与模型",
            "description": "智谱 AI 旗下 GLM 系列模型相关新闻",
            "keywords": ["智谱", "GLM", "ChatGLM", "GLM-4", "CodeGeeX", "CogView", "CogVideo"],
            "aliases": ["zhipu", "glm", "chatglm", "智谱"],
            "sort_order": 80,
            "is_active": 1,
        },
        {
            "name": "xAI / Grok",
            "slug": "xai-grok",
            "group_name": "公司与模型",
            "description": "xAI 旗下 Grok 系列模型相关新闻",
            "keywords": ["xAI", "Grok", "Elon Musk", "Grok-1", "Grok-2", "Grok-3", "X.com"],
            "aliases": ["xai", "grok", "elon musk"],
            "sort_order": 90,
            "is_active": 1,
        },
        {
            "name": "Meta / Llama",
            "slug": "meta-llama",
            "group_name": "公司与模型",
            "description": "Meta 旗下 Llama 系列开源模型相关新闻",
            "keywords": ["Meta", "Llama", "Llama 3", "Llama 4", "LLaMA", "Code Llama", "Zuckerberg", "FAIR"],
            "aliases": ["meta", "llama", "facebook"],
            "sort_order": 100,
            "is_active": 1,
        },
        {
            "name": "Microsoft / Copilot",
            "slug": "microsoft-copilot",
            "group_name": "公司与模型",
            "description": "微软 AI 产品与战略相关新闻，包括 Copilot、Azure AI、Phi 系列模型等",
            "keywords": ["Microsoft", "Copilot", "Azure AI", "Phi", "Phi-3", "Phi-4", "微软", "Satya Nadella"],
            "aliases": ["microsoft", "copilot", "msft", "微软", "azure"],
            "sort_order": 110,
            "is_active": 1,
        },
        {
            "name": "NVIDIA 英伟达",
            "slug": "nvidia",
            "group_name": "公司与模型",
            "description": "NVIDIA 芯片、AI 算力、CUDA 生态相关新闻",
            "keywords": ["NVIDIA", "英伟达", "GPU", "H100", "H200", "B100", "B200", "CUDA", "Jensen Huang", "黄仁勋"],
            "aliases": ["nvidia", "nvda", "英伟达"],
            "sort_order": 120,
            "is_active": 1,
        },
        {
            "name": "Hugging Face",
            "slug": "huggingface",
            "group_name": "公司与模型",
            "description": "Hugging Face 平台、开源工具、模型库相关新闻",
            "keywords": ["Hugging Face", "HuggingFace", "transformers", "diffusers", "datasets", "Gradio", "Spaces"],
            "aliases": ["huggingface", "hf"],
            "sort_order": 130,
            "is_active": 1,
        },
        {
            "name": "Cursor",
            "slug": "cursor",
            "group_name": "公司与模型",
            "description": "Cursor AI 编辑器及 Anysphere 公司相关新闻",
            "keywords": ["Cursor", "Anysphere", "AI editor", "AI IDE", "AI coding assistant"],
            "aliases": ["cursor", "anysphere"],
            "sort_order": 140,
            "is_active": 1,
        },
        {
            "name": "OpenRouter",
            "slug": "openrouter",
            "group_name": "公司与模型",
            "description": "OpenRouter API 网关及模型路由平台相关新闻",
            "keywords": ["OpenRouter", "model routing", "API gateway"],
            "aliases": ["openrouter"],
            "sort_order": 150,
            "is_active": 1,
        },

        # === 技术方向 ===
        {
            "name": "Agent 智能体",
            "slug": "ai-agent",
            "group_name": "技术方向",
            "description": "AI Agent、自主智能体、多 Agent 协作、工具使用相关进展",
            "keywords": ["Agent", "智能体", "AI agent", "autonomous agent", "multi-agent", "agentic", "SWE-agent", "Devin", "AutoGPT", "CrewAI", "LangGraph", "function calling"],
            "aliases": ["agent", "智能体", "agentic"],
            "sort_order": 10,
            "is_active": 1,
        },
        {
            "name": "AI 编码",
            "slug": "ai-coding",
            "group_name": "技术方向",
            "description": "AI 辅助编程、代码生成、代码理解、IDE 集成相关进展",
            "keywords": ["code generation", "AI coding", "Copilot", "Cursor", "code completion", "code review", "Devin", "SWE-bench", "Claude Code", "Aider", "Codex", "Windsurf"],
            "aliases": ["coding", "code", "编程", "代码"],
            "sort_order": 20,
            "is_active": 1,
        },
        {
            "name": "推理能力",
            "slug": "reasoning",
            "group_name": "技术方向",
            "description": "LLM 推理能力、Chain-of-Thought、数学推理、逻辑推理相关进展",
            "keywords": ["reasoning", "Chain-of-Thought", "CoT", "o1", "o3", "DeepSeek-R1", "推理", "math", "mathematical reasoning", "logical reasoning", "test-time compute", "scaling inference"],
            "aliases": ["reasoning", "推理", "cot", "chain-of-thought"],
            "sort_order": 30,
            "is_active": 1,
        },
        {
            "name": "多模态",
            "slug": "multimodal",
            "group_name": "技术方向",
            "description": "多模态模型、视觉语言模型、跨模态理解与生成相关进展",
            "keywords": ["multimodal", "多模态", "vision-language", "VLM", "GPT-4V", "GPT-4o", "Gemini Vision", "Claude Vision", "Qwen-VL", "visual understanding", "document understanding"],
            "aliases": ["multimodal", "多模态", "vlm", "vision"],
            "sort_order": 40,
            "is_active": 1,
        },
        {
            "name": "图像生成",
            "slug": "image-generation",
            "group_name": "技术方向",
            "description": "AI 图像生成、文生图、图像编辑模型与工具相关进展",
            "keywords": ["image generation", "文生图", "Stable Diffusion", "DALL-E", "Midjourney", "Flux", "SDXL", "SD3", "Imagen", "ControlNet", "IP-Adapter", "ComfyUI"],
            "aliases": ["image", "图像生成", "stable diffusion", "dalle", "midjourney", "flux"],
            "sort_order": 50,
            "is_active": 1,
        },
        {
            "name": "AI 视频",
            "slug": "ai-video",
            "group_name": "技术方向",
            "description": "AI 视频生成、视频理解、视频编辑模型与工具相关进展",
            "keywords": ["video generation", "AI video", "Sora", "Runway", "Pika", "Kling", "可灵", "Veo", "Luma", "视频生成", "video understanding"],
            "aliases": ["video", "视频", "sora", "runway", "kling", "veo"],
            "sort_order": 60,
            "is_active": 1,
        },
        {
            "name": "语音与音频",
            "slug": "speech-audio",
            "group_name": "技术方向",
            "description": "语音识别、语音合成、音频生成、实时对话 AI 相关进展",
            "keywords": ["speech", "audio", "TTS", "text-to-speech", "语音", "whisper", "ElevenLabs", "GPT-4o voice", "real-time", "voice assistant"],
            "aliases": ["speech", "audio", "语音", "tts", "voice"],
            "sort_order": 70,
            "is_active": 1,
        },
        {
            "name": "具身智能",
            "slug": "embodied-ai",
            "group_name": "技术方向",
            "description": "具身智能、机器人、自动驾驶、物理世界 AI 相关进展",
            "keywords": ["embodied", "robot", "robotics", "具身智能", "机器人", "self-driving", "autonomous driving", "自动驾驶", "Figure", "Tesla Bot", "Optimus", "physical AI"],
            "aliases": ["embodied", "robot", "具身智能", "机器人"],
            "sort_order": 80,
            "is_active": 1,
        },
        {
            "name": "端侧 AI",
            "slug": "on-device-ai",
            "group_name": "技术方向",
            "description": "端侧推理、手机/PC AI、芯片、边缘计算相关进展",
            "keywords": ["on-device", "edge", "端侧", "Apple Intelligence", "Qualcomm", "MediaTek", "NPU", "llama.cpp", "ollama", "MLX", "Gemma", "Phi", "mobile", "local LLM"],
            "aliases": ["on-device", "edge", "端侧", "local", "mobile", "ollama"],
            "sort_order": 90,
            "is_active": 1,
        },
        {
            "name": "开源生态",
            "slug": "open-source-ecosystem",
            "group_name": "技术方向",
            "description": "开源 AI 模型、框架、工具、社区动态相关新闻",
            "keywords": ["open source", "开源", "open weights", "open model", "Apache", "MIT", "Llama", "Mistral", "Falcon", "OLMo", "Llama.cpp", "vLLM", "community"],
            "aliases": ["open source", "开源", "open-source", "oss"],
            "sort_order": 100,
            "is_active": 1,
        },
        {
            "name": "部署工程",
            "slug": "deployment-engineering",
            "group_name": "技术方向",
            "description": "模型部署、推理优化、服务框架、企业 AI 落地相关进展",
            "keywords": ["deployment", "部署", "serving", "inference optimization", "quantization", "量化", "vLLM", "TGI", "TensorRT", "GGUF", "AWQ", "speculative decoding", "KV cache", "enterprise", "企业部署"],
            "aliases": ["deployment", "部署", "serving", "inference", "推理优化"],
            "sort_order": 110,
            "is_active": 1,
        },
        {
            "name": "数据与训练",
            "slug": "data-training",
            "group_name": "技术方向",
            "description": "训练数据、合成数据、预训练、微调、RLHF、数据标注相关进展",
            "keywords": ["training", "训练", "finetuning", "微调", "RLHF", "DPO", "GRPO", "synthetic data", "合成数据", "pretraining", "curriculum learning", "data annotation", "数据标注", "SFT", "LoRA", "QLoRA"],
            "aliases": ["training", "训练", "finetuning", "微调", "rlhf", "dpo"],
            "sort_order": 120,
            "is_active": 1,
        },
        {
            "name": "安全对齐",
            "slug": "safety-alignment",
            "group_name": "技术方向",
            "description": "AI 安全、对齐、红队测试、越狱防御、价值观对齐相关进展",
            "keywords": ["safety", "安全", "alignment", "对齐", "red teaming", "jailbreak", "越狱", "RLHF", "Constitutional AI", "harmlessness", "responsible AI", "AI ethics"],
            "aliases": ["safety", "安全", "alignment", "对齐", "jailbreak", "red team"],
            "sort_order": 130,
            "is_active": 1,
        },
        {
            "name": "MCP 与工具调用",
            "slug": "mcp-tool-use",
            "group_name": "技术方向",
            "description": "Model Context Protocol、工具调用、插件系统、API 集成相关进展",
            "keywords": ["MCP", "Model Context Protocol", "tool use", "function calling", "plugin", "Anthropic MCP", "工具调用", "tool calling", "API integration"],
            "aliases": ["mcp", "tool use", "function calling", "工具调用"],
            "sort_order": 140,
            "is_active": 1,
        },

        # === 内容形态 ===
        {
            "name": "模型发布",
            "slug": "model-release",
            "group_name": "内容形态",
            "description": "新模型、模型新版本、模型 checkpoint 发布",
            "keywords": ["模型发布", "model release", "new model", "launch", "发布", "checkpoint", "weights", "open source release"],
            "aliases": ["release", "发布", "模型发布"],
            "sort_order": 10,
            "is_active": 1,
        },
        {
            "name": "产品更新",
            "slug": "product-update",
            "group_name": "内容形态",
            "description": "产品功能更新、新功能上线、产品迭代",
            "keywords": ["产品更新", "product update", "new feature", "功能更新", "rollout", "推出", "上线", "upgrade"],
            "aliases": ["product", "产品", "update", "更新"],
            "sort_order": 20,
            "is_active": 1,
        },
        {
            "name": "论文研究",
            "slug": "paper-research",
            "group_name": "内容形态",
            "description": "学术论文、技术报告、研究成果",
            "keywords": ["论文", "paper", "research", "研究", "arxiv", "preprint", "conference", "NeurIPS", "ICML", "ICLR", "CVPR", "ACL", "EMNLP"],
            "aliases": ["paper", "论文", "research", "研究", "arxiv"],
            "sort_order": 30,
            "is_active": 1,
        },
        {
            "name": "评测基准",
            "slug": "benchmark-evaluation",
            "group_name": "内容形态",
            "description": "模型评测、基准测试、排行榜、性能对比",
            "keywords": ["评测", "benchmark", "evaluation", "leaderboard", "LMSYS", "Chatbot Arena", "MMLU", "HumanEval", "SWE-bench", "AIME"],
            "aliases": ["benchmark", "评测", "evaluation", "evaluation"],
            "sort_order": 40,
            "is_active": 1,
        },
        {
            "name": "教程实践",
            "slug": "tutorial-practice",
            "group_name": "内容形态",
            "description": "教程、实践指南、技术分享、踩坑经验",
            "keywords": ["教程", "tutorial", "guide", "how-to", "实践", "hands-on", "workshop", "教程", "指南"],
            "aliases": ["tutorial", "教程", "guide", "实践"],
            "sort_order": 50,
            "is_active": 1,
        },
        {
            "name": "大佬观点",
            "slug": "expert-opinion",
            "group_name": "内容形态",
            "description": "行业领袖、知名研究者、企业高管的观点、预测、评论",
            "keywords": ["观点", "opinion", "预测", "commentary", "interview", "采访", "预测", "展望", "think piece"],
            "aliases": ["opinion", "观点", "commentary", "评论"],
            "sort_order": 60,
            "is_active": 1,
        },
        {
            "name": "现象与趋势",
            "slug": "phenomenon-trend",
            "group_name": "内容形态",
            "description": "行业现象、趋势分析、数据报告、市场研究",
            "keywords": ["趋势", "trend", "现象", "报告", "report", "统计", "数据", "分析", "预测", "增长", "survey"],
            "aliases": ["trend", "趋势", "现象", "报告"],
            "sort_order": 70,
            "is_active": 1,
        },
        {
            "name": "行业动态",
            "slug": "industry-news",
            "group_name": "内容形态",
            "description": "AI 行业商业动态，包括投融资、合作、竞争、人事变动、公司战略",
            "keywords": ["行业动态", "industry", "投融资", "acquisition", "收购", "融资", "funding", "IPO", "合作", "partnership", "竞争", "裁员", "layoff", "战略"],
            "aliases": ["industry", "行业", "投融资", "funding", "收购", "合作"],
            "sort_order": 80,
            "is_active": 1,
        },
        {
            "name": "政策监管",
            "slug": "policy-regulation",
            "group_name": "内容形态",
            "description": "AI 政策、法律法规、监管框架、合规要求",
            "keywords": ["政策", "policy", "监管", "regulation", "法规", "法律", "欧盟", "EU AI Act", "白宫", "行政令", "国会", "数据隐私", "GDPR", "版权", "copyright"],
            "aliases": ["policy", "政策", "regulation", "监管", "法律"],
            "sort_order": 90,
            "is_active": 1,
        },
    ]
